#!/bin/bash
# comment out any lines you don't want to download!
# canvasDataCli fetch -c /usr/lib/node_modules/canvas-data-cli/config.js -t account_dim
# canvasDataCli fetch -c /usr/lib/node_modules/canvas-data-cli/config.js -t assignment_dim
# canvasDataCli fetch -c /usr/lib/node_modules/canvas-data-cli/config.js -t assignment_fact
# canvasDataCli fetch -c /usr/lib/node_modules/canvas-data-cli/config.js -t assignment_group_dim
# canvasDataCli fetch -c /usr/lib/node_modules/canvas-data-cli/config.js -t assignment_group_fact
# canvasDataCli fetch -c /usr/lib/node_modules/canvas-data-cli/config.js -t assignment_group_rule_dim
# canvasDataCli fetch -c /usr/lib/node_modules/canvas-data-cli/config.js -t assignment_group_score_dim
# canvasDataCli fetch -c /usr/lib/node_modules/canvas-data-cli/config.js -t assignment_group_score_fact
# canvasDataCli fetch -c /usr/lib/node_modules/canvas-data-cli/config.js -t assignment_override_dim
# canvasDataCli fetch -c /usr/lib/node_modules/canvas-data-cli/config.js -t assignment_override_fact
# canvasDataCli fetch -c /usr/lib/node_modules/canvas-data-cli/config.js -t assignment_override_user_dim
# canvasDataCli fetch -c /usr/lib/node_modules/canvas-data-cli/config.js -t assignment_override_user_fact
# canvasDataCli fetch -c /usr/lib/node_modules/canvas-data-cli/config.js -t assignment_override_user_rollup_fact
# canvasDataCli fetch -c /usr/lib/node_modules/canvas-data-cli/config.js -t assignment_rule_dim
# canvasDataCli fetch -c /usr/lib/node_modules/canvas-data-cli/config.js -t communication_channel_dim
# canvasDataCli fetch -c /usr/lib/node_modules/canvas-data-cli/config.js -t communication_channel_fact
# canvasDataCli fetch -c /usr/lib/node_modules/canvas-data-cli/config.js -t conference_dim
# canvasDataCli fetch -c /usr/lib/node_modules/canvas-data-cli/config.js -t conference_fact
# canvasDataCli fetch -c /usr/lib/node_modules/canvas-data-cli/config.js -t conference_participant_dim
# canvasDataCli fetch -c /usr/lib/node_modules/canvas-data-cli/config.js -t conference_participant_fact
# canvasDataCli fetch -c /usr/lib/node_modules/canvas-data-cli/config.js -t conversation_dim
# canvasDataCli fetch -c /usr/lib/node_modules/canvas-data-cli/config.js -t conversation_message_dim
# canvasDataCli fetch -c /usr/lib/node_modules/canvas-data-cli/config.js -t conversation_message_participant_fact
# canvasDataCli fetch -c /usr/lib/node_modules/canvas-data-cli/config.js -t course_dim
# canvasDataCli fetch -c /usr/lib/node_modules/canvas-data-cli/config.js -t course_score_dim
# canvasDataCli fetch -c /usr/lib/node_modules/canvas-data-cli/config.js -t course_score_fact
# canvasDataCli fetch -c /usr/lib/node_modules/canvas-data-cli/config.js -t course_section_dim
# canvasDataCli fetch -c /usr/lib/node_modules/canvas-data-cli/config.js -t course_ui_canvas_navigation_dim
# canvasDataCli fetch -c /usr/lib/node_modules/canvas-data-cli/config.js -t course_ui_navigation_item_dim
# canvasDataCli fetch -c /usr/lib/node_modules/canvas-data-cli/config.js -t course_ui_navigation_item_fact
# canvasDataCli fetch -c /usr/lib/node_modules/canvas-data-cli/config.js -t discussion_entry_dim
# canvasDataCli fetch -c /usr/lib/node_modules/canvas-data-cli/config.js -t discussion_entry_fact
# canvasDataCli fetch -c /usr/lib/node_modules/canvas-data-cli/config.js -t discussion_topic_dim
# canvasDataCli fetch -c /usr/lib/node_modules/canvas-data-cli/config.js -t discussion_topic_fact
# canvasDataCli fetch -c /usr/lib/node_modules/canvas-data-cli/config.js -t enrollment_dim
# canvasDataCli fetch -c /usr/lib/node_modules/canvas-data-cli/config.js -t enrollment_fact
# canvasDataCli fetch -c /usr/lib/node_modules/canvas-data-cli/config.js -t enrollment_rollup_dim
# canvasDataCli fetch -c /usr/lib/node_modules/canvas-data-cli/config.js -t enrollment_term_dim
# canvasDataCli fetch -c /usr/lib/node_modules/canvas-data-cli/config.js -t external_tool_activation_dim
# canvasDataCli fetch -c /usr/lib/node_modules/canvas-data-cli/config.js -t external_tool_activation_fact
# canvasDataCli fetch -c /usr/lib/node_modules/canvas-data-cli/config.js -t file_dim
# canvasDataCli fetch -c /usr/lib/node_modules/canvas-data-cli/config.js -t file_fact
# canvasDataCli fetch -c /usr/lib/node_modules/canvas-data-cli/config.js -t grading_period_dim
# canvasDataCli fetch -c /usr/lib/node_modules/canvas-data-cli/config.js -t grading_period_fact
# canvasDataCli fetch -c /usr/lib/node_modules/canvas-data-cli/config.js -t grading_period_group_dim
# canvasDataCli fetch -c /usr/lib/node_modules/canvas-data-cli/config.js -t grading_period_score_dim
# canvasDataCli fetch -c /usr/lib/node_modules/canvas-data-cli/config.js -t grading_period_score_fact
# canvasDataCli fetch -c /usr/lib/node_modules/canvas-data-cli/config.js -t group_dim
# canvasDataCli fetch -c /usr/lib/node_modules/canvas-data-cli/config.js -t group_fact
# canvasDataCli fetch -c /usr/lib/node_modules/canvas-data-cli/config.js -t group_membership_dim
# canvasDataCli fetch -c /usr/lib/node_modules/canvas-data-cli/config.js -t group_membership_fact
# canvasDataCli fetch -c /usr/lib/node_modules/canvas-data-cli/config.js -t learning_outcome_fact
# canvasDataCli fetch -c /usr/lib/node_modules/canvas-data-cli/config.js -t learning_outcome_dim
# canvasDataCli fetch -c /usr/lib/node_modules/canvas-data-cli/config.js -t learning_outcome_group_association_fact
# canvasDataCli fetch -c /usr/lib/node_modules/canvas-data-cli/config.js -t learning_outcome_group_dim
# canvasDataCli fetch -c /usr/lib/node_modules/canvas-data-cli/config.js -t learning_outcome_group_fact
# canvasDataCli fetch -c /usr/lib/node_modules/canvas-data-cli/config.js -t learning_outcome_question_result_dim
# canvasDataCli fetch -c /usr/lib/node_modules/canvas-data-cli/config.js -t learning_outcome_question_result_fact
# canvasDataCli fetch -c /usr/lib/node_modules/canvas-data-cli/config.js -t learning_outcome_result_dim
# canvasDataCli fetch -c /usr/lib/node_modules/canvas-data-cli/config.js -t learning_outcome_result_fact
# canvasDataCli fetch -c /usr/lib/node_modules/canvas-data-cli/config.js -t learning_outcome_rubric_criterion_dim
# canvasDataCli fetch -c /usr/lib/node_modules/canvas-data-cli/config.js -t learning_outcome_rubric_criterion_fact
# canvasDataCli fetch -c /usr/lib/node_modules/canvas-data-cli/config.js -t module_completion_requirement_dim
# canvasDataCli fetch -c /usr/lib/node_modules/canvas-data-cli/config.js -t module_completion_requirement_fact
# canvasDataCli fetch -c /usr/lib/node_modules/canvas-data-cli/config.js -t module_dim
# canvasDataCli fetch -c /usr/lib/node_modules/canvas-data-cli/config.js -t module_fact
# canvasDataCli fetch -c /usr/lib/node_modules/canvas-data-cli/config.js -t module_item_dim
# canvasDataCli fetch -c /usr/lib/node_modules/canvas-data-cli/config.js -t module_item_fact
# canvasDataCli fetch -c /usr/lib/node_modules/canvas-data-cli/config.js -t module_prerequisite_dim
# canvasDataCli fetch -c /usr/lib/node_modules/canvas-data-cli/config.js -t module_prerequisite_fact
# canvasDataCli fetch -c /usr/lib/node_modules/canvas-data-cli/config.js -t module_progression_completion_requirement_dim
# canvasDataCli fetch -c /usr/lib/node_modules/canvas-data-cli/config.js -t module_progression_completion_requirement_fact
# canvasDataCli fetch -c /usr/lib/node_modules/canvas-data-cli/config.js -t module_progression_dim
# canvasDataCli fetch -c /usr/lib/node_modules/canvas-data-cli/config.js -t module_progression_fact
# canvasDataCli fetch -c /usr/lib/node_modules/canvas-data-cli/config.js -t pseudonym_dim
# canvasDataCli fetch -c /usr/lib/node_modules/canvas-data-cli/config.js -t pseudonym_fact
# canvasDataCli fetch -c /usr/lib/node_modules/canvas-data-cli/config.js -t quiz_dim
# canvasDataCli fetch -c /usr/lib/node_modules/canvas-data-cli/config.js -t quiz_fact
# canvasDataCli fetch -c /usr/lib/node_modules/canvas-data-cli/config.js -t quiz_question_answer_dim
# canvasDataCli fetch -c /usr/lib/node_modules/canvas-data-cli/config.js -t quiz_question_answer_fact
# canvasDataCli fetch -c /usr/lib/node_modules/canvas-data-cli/config.js -t quiz_question_dim
# canvasDataCli fetch -c /usr/lib/node_modules/canvas-data-cli/config.js -t quiz_question_fact
# canvasDataCli fetch -c /usr/lib/node_modules/canvas-data-cli/config.js -t quiz_question_group_dim
# canvasDataCli fetch -c /usr/lib/node_modules/canvas-data-cli/config.js -t quiz_question_group_fact
# canvasDataCli fetch -c /usr/lib/node_modules/canvas-data-cli/config.js -t quiz_submission_dim
# canvasDataCli fetch -c /usr/lib/node_modules/canvas-data-cli/config.js -t quiz_submission_fact
# canvasDataCli fetch -c /usr/lib/node_modules/canvas-data-cli/config.js -t quiz_submission_historical_dim
# canvasDataCli fetch -c /usr/lib/node_modules/canvas-data-cli/config.js -t quiz_submission_historical_fact
# canvasDataCli fetch -c /usr/lib/node_modules/canvas-data-cli/config.js -t role_dim
# canvasDataCli fetch -c /usr/lib/node_modules/canvas-data-cli/config.js -t submission_comment_dim
# canvasDataCli fetch -c /usr/lib/node_modules/canvas-data-cli/config.js -t submission_comment_fact
# canvasDataCli fetch -c /usr/lib/node_modules/canvas-data-cli/config.js -t submission_comment_participant_dim
# canvasDataCli fetch -c /usr/lib/node_modules/canvas-data-cli/config.js -t submission_comment_participant_fact
# canvasDataCli fetch -c /usr/lib/node_modules/canvas-data-cli/config.js -t submission_dim
# canvasDataCli fetch -c /usr/lib/node_modules/canvas-data-cli/config.js -t submission_fact
# canvasDataCli fetch -c /usr/lib/node_modules/canvas-data-cli/config.js -t submission_file_fact
# canvasDataCli fetch -c /usr/lib/node_modules/canvas-data-cli/config.js -t user_dim
# canvasDataCli fetch -c /usr/lib/node_modules/canvas-data-cli/config.js -t wiki_dim
# canvasDataCli fetch -c /usr/lib/node_modules/canvas-data-cli/config.js -t wiki_fact
# canvasDataCli fetch -c /usr/lib/node_modules/canvas-data-cli/config.js -t wiki_page_dim
# canvasDataCli fetch -c /usr/lib/node_modules/canvas-data-cli/config.js -t wiki_page_fact
